-- Snapshot storico sostituito dalle migrazioni versionate.
-- Applicare, nell'ordine, i file presenti in supabase/migrations/.
-- Migrazione iniziale: migrations/20260716180000_initial_secure_schema.sql
