import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { hasValidOrigin } from "@/lib/security";
import { contentSections, sanitizeContentValue } from "@/lib/site-content";

async function getAdmin(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return null;const {data:profile}=await supabase.from("profiles").select("role,is_active").eq("id",user.id).single();return profile?.role==="admin"&&profile.is_active?{supabase,user}:null}
export async function GET(){const admin=await getAdmin();if(!admin)return NextResponse.json({error:"Accesso negato."},{status:403});const {data,error}=await admin.supabase.from("site_content").select("content_key,value,is_published,updated_at").in("content_key",contentSections.map(section=>section.key));if(error)return NextResponse.json({error:"Contenuti non disponibili."},{status:400});return NextResponse.json({content:data??[]})}
export async function PATCH(request:Request){if(!hasValidOrigin(request))return NextResponse.json({error:"Origine non consentita."},{status:403});const admin=await getAdmin();if(!admin)return NextResponse.json({error:"Accesso negato."},{status:403});const body=await request.json().catch(()=>null) as {key?:string;value?:unknown}|null;const definition=contentSections.find(section=>section.key===body?.key);if(!definition)return NextResponse.json({error:"Sezione non consentita."},{status:400});const sanitized=sanitizeContentValue(body?.value);const value=Object.fromEntries(definition.fields.map(field=>[field.name,sanitized[field.name]??definition.defaults[field.name]??""]));const {error}=await admin.supabase.from("site_content").upsert({content_key:definition.key,locale:"it",value,is_published:true,published_at:new Date().toISOString(),updated_by:admin.user.id},{onConflict:"content_key"});if(error)return NextResponse.json({error:"Salvataggio non riuscito."},{status:400});return NextResponse.json({ok:true,value})}
export async function DELETE(request:Request){if(!hasValidOrigin(request))return NextResponse.json({error:"Origine non consentita."},{status:403});const admin=await getAdmin();if(!admin)return NextResponse.json({error:"Accesso negato."},{status:403});const body=await request.json().catch(()=>null) as {key?:string}|null;if(!contentSections.some(section=>section.key===body?.key))return NextResponse.json({error:"Sezione non consentita."},{status:400});const {error}=await admin.supabase.from("site_content").delete().eq("content_key",body!.key!);if(error)return NextResponse.json({error:"Ripristino non riuscito."},{status:400});return NextResponse.json({ok:true})}
