export type ContentField = { name:string; label:string; help:string; multiline?:boolean };
export type ContentSection = { key:string; page:string; title:string; fields:ContentField[]; defaults:Record<string,string> };

export const contentSections:ContentSection[]=[
  {key:"home.hero",page:"Homepage",title:"Hero principale",fields:[{name:"eyebrow",label:"Sovratitolo",help:"Sopra il titolo"},{name:"title",label:"Titolo",help:"Prima riga"},{name:"highlight",label:"Titolo evidenziato",help:"Seconda riga"},{name:"body",label:"Sottotitolo",help:"Testo introduttivo",multiline:true},{name:"primary",label:"Pulsante principale",help:"Prenotazione"},{name:"secondary",label:"Pulsante secondario",help:"Servizi"}],defaults:{eyebrow:"Personal Trainer · Online e in presenza",title:"Prenditi cura di te,",highlight:"un allenamento alla volta.",body:"Allenamento personalizzato, metodo e supporto costante per costruire risultati concreti e sostenibili.",primary:"Prenota una consulenza",secondary:"Scopri i servizi"}},
  {key:"home.intro",page:"Homepage",title:"Presentazione",fields:[{name:"title",label:"Titolo",help:"Sezione introduttiva",multiline:true},{name:"body",label:"Testo",help:"Presentazione sintetica",multiline:true},{name:"link",label:"Testo collegamento",help:"Link alla pagina Chi sono"}],defaults:{title:"Allenarsi bene significa sentirsi capiti, prima ancora che guidati.",body:"Sono Francesco Crivello, Personal Trainer. Partiamo dall’ascolto, definiamo obiettivi realistici e costruiamo un percorso progressivo.",link:"Conosci Francesco"}},
  {key:"home.cta",page:"Homepage",title:"Call to action finale",fields:[{name:"title",label:"Titolo",help:"Invito finale"},{name:"body",label:"Descrizione",help:"Testo sotto il titolo",multiline:true},{name:"button",label:"Pulsante",help:"Testo del pulsante"}],defaults:{title:"Parliamo dei tuoi obiettivi.",body:"Una consulenza conoscitiva, senza pressioni, per capire insieme da dove partire.",button:"Prenota una consulenza"}},
  {key:"about.main",page:"Chi sono",title:"Presentazione professionale",fields:[{name:"title",label:"Titolo",help:"Hero della pagina",multiline:true},{name:"body",label:"Presentazione",help:"Profilo professionale",multiline:true},{name:"training",label:"Formazione",help:"Percorso formativo",multiline:true},{name:"certifications",label:"Certificazioni",help:"Certificazioni verificate",multiline:true},{name:"philosophy",label:"Filosofia",help:"Citazione conclusiva",multiline:true}],defaults:{title:"Competenza, ascolto e un metodo che si adatta.",body:"Sono Francesco Crivello, Personal Trainer. Credo in un allenamento costruito con cura e sostenibile nella vita reale.",training:"Formazione professionale da completare.",certifications:"Certificazioni da completare.",philosophy:"Non inseguo scorciatoie. Costruiamo capacità, fiducia e abitudini che possano restare."}},
  {key:"services.page",page:"Servizi",title:"Intestazione pagina",fields:[{name:"title",label:"Titolo",help:"Intestazione"},{name:"body",label:"Descrizione",help:"Introduzione al catalogo",multiline:true}],defaults:{title:"Un allenamento che parla di te.",body:"Ogni servizio è un punto di partenza. Il percorso viene adattato a obiettivi, esperienza e disponibilità."}},
  {key:"contact.main",page:"Contatti",title:"Contatti pubblici",fields:[{name:"title",label:"Titolo",help:"Intestazione"},{name:"body",label:"Descrizione",help:"Introduzione al modulo",multiline:true},{name:"phone",label:"Telefono",help:"Recapito pubblico"},{name:"email",label:"Email",help:"Recapito pubblico"},{name:"instagram",label:"Instagram",help:"Profilo social"}],defaults:{title:"Raccontami da dove vuoi partire.",body:"Compila il modulo: ti ricontatterò per capire insieme il passo successivo.",phone:"+39 000 000 0000",email:"ciao@francescocrivello.it",instagram:"@francescocrivello.pt"}},
  {key:"forms.booking",page:"Form e messaggi",title:"Prenotazione",fields:[{name:"title",label:"Titolo modulo",help:"Pagina prenotazione"},{name:"confirmation",label:"Conferma",help:"Dopo il salvataggio",multiline:true},{name:"account_invite",label:"Invito account",help:"Dopo una prenotazione ospite",multiline:true}],defaults:{title:"Prenota il tuo appuntamento",confirmation:"Richiesta inviata correttamente.",account_invite:"Crea un account per seguire lo stato della prenotazione e gestire più comodamente le richieste future."}},
  {key:"legal.privacy",page:"Pagine legali",title:"Privacy policy",fields:[{name:"title",label:"Titolo",help:"Titolo documento"},{name:"intro",label:"Introduzione",help:"Testo iniziale",multiline:true},{name:"body",label:"Contenuto",help:"Testo semplice, senza HTML",multiline:true}],defaults:{title:"Privacy policy",intro:"Informativa sul trattamento dei dati personali.",body:"Documento da completare e verificare con il consulente legale."}},
  {key:"legal.terms",page:"Pagine legali",title:"Regolamento prenotazioni",fields:[{name:"title",label:"Titolo",help:"Titolo documento"},{name:"intro",label:"Introduzione",help:"Testo iniziale",multiline:true},{name:"body",label:"Contenuto",help:"Testo semplice, senza HTML",multiline:true}],defaults:{title:"Termini e regolamento prenotazioni",intro:"Regole applicabili a modifiche, cancellazioni e ritardi.",body:"Le condizioni definitive devono essere verificate e pubblicate dal titolare."}},
  {key:"footer.main",page:"Footer",title:"Informazioni footer",fields:[{name:"text",label:"Testo",help:"Breve descrizione",multiline:true},{name:"credits",label:"Crediti",help:"Riga finale"}],defaults:{text:"Personal training online, a domicilio e nella palestra del cliente.",credits:"Francesco Crivello · Personal Trainer"}},
];

export function sanitizeContentValue(value:unknown):Record<string,string>{const result:Record<string,string>={};if(!value||typeof value!=="object"||Array.isArray(value))return result;for(const [key,item] of Object.entries(value))if(/^[a-z0-9_]+$/i.test(key)&&typeof item==="string")result[key]=item.replace(/<\/?script\b[^>]*>/gi,"").slice(0,20000);return result}
